title: "Jiwon Kim, Ph. D."
description: 
url: "https://jiwoncellmechanics.github.io"
baseurl: ""

theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt"

plugins:
  - jekyll-include-cache
